/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerTeman;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelTeman;
import util.Koneksi;

/**
 *
 * @author DELL
 */
public class ViewTeman extends javax.swing.JFrame {
    Koneksi koneksi=new Koneksi();
        ControllerTeman ct=new ControllerTeman();
        ModelTeman mt=new ModelTeman();
    /**
     * Creates new form ViewTeman
     */
    public ViewTeman() {
        initComponents();
        datatable();
        
    }
    private void baru(){
        jB_baru.setEnabled(false);
        jB_simpan.setEnabled(true);
        jB_ubah.setEnabled(false);
        jB_hapus.setEnabled(false);
        jT_nama.setEditable(true);
        jT_nope.setEditable(true);
        jT_email.setEditable(true);
    }
    private void bersih(){
        jT_id.setText(" ");
        jT_nama.setText(" ");
        jT_nope.setText(" ");
        jT_email.setText(" ");

        jB_baru.setEnabled(true);
        jB_simpan.setEnabled(false);
        jB_hapus.setEnabled(false);
        jB_ubah.setEnabled(false);
        jB_bersih.setEnabled(false);
        jT_nama.setEditable(false);
        jT_nope.setEditable(false);
        jT_email.setEditable(false);
        datatable();
    }
    private void datatable(){
        koneksi.koneksiDatabase();

        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("Nope");
        tabel.addColumn("Email");

        jTable1.setModel(tabel);
        try {
            String sql="select * from tbl_teman";
            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next());
            tabel.addRow(new Object[]{
                   res.getString("id"),
                   res.getString("nama"),
                   res.getString("nope"),
                   res.getString("email")
        });
            jTable1.setModel(tabel);
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jT_id = new javax.swing.JTextField();
        jT_nama = new javax.swing.JTextField();
        jT_nope = new javax.swing.JTextField();
        jT_email = new javax.swing.JTextField();
        jB_baru = new javax.swing.JButton();
        jB_ubah = new javax.swing.JButton();
        jB_simpan = new javax.swing.JButton();
        jB_hapus = new javax.swing.JButton();
        jB_bersih = new javax.swing.JButton();
        jB_tutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setText("nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setText("No. Hp");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jT_id.setEnabled(false);
        jT_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_idActionPerformed(evt);
            }
        });
        getContentPane().add(jT_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 70, -1));
        getContentPane().add(jT_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, 30));
        getContentPane().add(jT_nope, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));
        getContentPane().add(jT_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        jB_baru.setText("Baru");
        jB_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_baruActionPerformed(evt);
            }
        });
        getContentPane().add(jB_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, -1));

        jB_ubah.setText("Ubah");
        jB_ubah.setEnabled(false);
        jB_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(jB_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 70, -1));

        jB_simpan.setText("Simpan");
        jB_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(jB_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 70, -1));

        jB_hapus.setText("Hapus");
        jB_hapus.setEnabled(false);
        jB_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(jB_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, -1));

        jB_bersih.setText("Bersih");
        jB_bersih.setEnabled(false);
        jB_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_bersihActionPerformed(evt);
            }
        });
        getContentPane().add(jB_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 70, -1));

        jB_tutup.setText("Tutup");
        jB_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_tutupActionPerformed(evt);
            }
        });
        getContentPane().add(jB_tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 70, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No.Hp", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_idActionPerformed

    private void jB_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String nama = jT_nama.getText();
            String nope = jT_nope.getText();
            String email = jT_email.getText();
            mt.setNama(nama);
            mt.setNope(nope);
            mt.setEmail(email);
            ct.simpanData(mt);
            datatable();
            bersih();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Silahkan Masukkan Angka");
            jT_nope.setText("");
            jT_nope.requestFocus();
        }
    }//GEN-LAST:event_jB_simpanActionPerformed

    private void jB_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_baruActionPerformed
        // TODO add your handling code here:
        baru();
    }//GEN-LAST:event_jB_baruActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            int baris = jTable1.getSelectedRow();
            jT_id.setText(jTable1.getValueAt(baris, 0).toString());
            jT_nama.setText(jTable1.getValueAt(baris, 1).toString());
            jT_nope.setText(jTable1.getValueAt(baris, 2).toString());
            jT_email.setText(jTable1.getValueAt(baris, 3).toString());
        } catch (Exception e) {
            System.err.println("Error : " + e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jB_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_hapusActionPerformed
        // TODO add your handling code here:
        try {
            int id=Integer.parseInt(jT_id.getText());
            mt.setId(id);
            ct.hapusData(mt);
            
            datatable();
            bersih();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Harap Masukkan data");
        }
    }//GEN-LAST:event_jB_hapusActionPerformed

    private void jB_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ubahActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jT_id.getText());
            String nama = jT_nama.getText();
            String nope = jT_nope.getText();
            String email = jT_email.getText();
            
            mt.setId(id);
            mt.setNama(nama);
            mt.setNope(nope);
            mt.setEmail(email);
            ct.ubahData(mt);
            
            bersih();
            datatable();
            
        } catch (NullPointerException e) {
            
        }
    }//GEN-LAST:event_jB_ubahActionPerformed

    private void jB_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_bersihActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jB_bersihActionPerformed

    private void jB_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_tutupActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jB_tutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_baru;
    private javax.swing.JButton jB_bersih;
    private javax.swing.JButton jB_hapus;
    private javax.swing.JButton jB_simpan;
    private javax.swing.JButton jB_tutup;
    private javax.swing.JButton jB_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_email;
    private javax.swing.JTextField jT_id;
    private javax.swing.JTextField jT_nama;
    private javax.swing.JTextField jT_nope;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
